# Generated by Django 4.0.5 on 2022-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_greatproduct_price_alter_greatproduct_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
