# Generated by Django 4.0.5 on 2022-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratings',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
