# Generated by Django 4.0.5 on 2022-07-05 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_userratings_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userratings',
            unique_together={('user', 'product')},
        ),
    ]
