# Generated by Django 4.0.5 on 2022-07-05 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userratings_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
